name: ci

on:
  push:
  pull_request:
  workflow_dispatch:  # allows you to run manually

jobs:
  test-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest

      - name: Run unit tests
        # Add repo root to PYTHONPATH so imports like "from src..." work
        run: |
          export PYTHONPATH=.
          pytest -q

      - name: Run tool execution task
        run: |
          export PYTHONPATH=.
          python -m src.run_once --task pytest --path workspace --out artifacts/report.md

      - name: Upload test artifact
        uses: actions/upload-artifact@v4
        with:
          name: execution-report
          path: artifacts/report.md

