name: ci

on:
  push:
  pull_request:
  workflow_dispatch:  # allows the Run workflow button

jobs:
  test-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Unit tests
        run: pytest -q
      - name: Tool execution (pytest on workspace)
        run: python -m src.run_once --task pytest --path workspace --out artifacts/report.md
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: execution-report
          path: artifacts/report.md
