name: ci

on:
  push:
  pull_request:
  workflow_dispatch:  # enables the "Run workflow" button

jobs:
  test-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install project
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Unit tests
        # Ensure Python can import from repo root so "src" resolves
        run: |
          PYTHONPATH=. pytest -q

      - name: Tool execution (pytest on workspace)
        run: |
          PYTHONPATH=. python -m src.run_once --task pytest --path workspace --out artifacts/report.md

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: execution-report
          path: artifacts/report.md
