name: ci

on:
  push:
  pull_request:
  workflow_dispatch:  # allows manual runs

jobs:
  test-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .

      - name: Verify project structure
        run: ls -R

      - name: Run unit tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          echo "PYTHONPATH is $PYTHONPATH"
          pytest -v

      - name: Tool execution (pytest on workspace)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python -m src.run_once --task pytest --path workspace --out artifacts/report.md

      - name: Upload test artifact
        uses: actions/upload-artifact@v4
        with:
          name: execution-report
          path: artifacts/report.md


